name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 'openjdk8', 'openjdk11' ]
    name: Java ${{ matrix.java }} sample
    steps:
      - uses: actions/checkout@master
      - name: Setup java
        uses: joschi/setup-jdk@v1
        with:
          java-version: ${{ matrix.java }}
      run: ./gradlew
