name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java_version: [1.8, 11]
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK $
        uses: actions/setup-java@v1
        with:
          java-version: $
    - name: Gradle
      run: ./gradlew
